<?xml version="1.0" encoding="utf-8"?><Database Name="FastFoodManagementDB" Class="FastFoodManagementDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=XOENXOEN\XOEN;Initial Catalog=FastFoodManagementDB;Integrated Security=True;Encrypt=True" SettingsObjectName="DTO.Properties.Settings" SettingsPropertyName="FastFoodManagementDBConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.admin_roles" Member="admin_roles">
    <Type Name="admin_role">
      <Column Name="admin_id" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="role_id" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="admin_admin_role" Member="admin" ThisKey="admin_id" OtherKey="admin_id" Type="admin" IsForeignKey="true" />
      <Association Name="role_admin_role" Member="role" ThisKey="role_id" OtherKey="role_id" Type="role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.shopping_cart" Member="shopping_carts">
    <Type Name="shopping_cart">
      <Column Name="shopping_cart_id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="total_items" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="total_price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="customer_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="shopping_cart_cart_item" Member="cart_items" ThisKey="shopping_cart_id" OtherKey="shopping_cart_id" Type="cart_item" />
      <Association Name="customer_shopping_cart" Member="customer" ThisKey="customer_id" OtherKey="customer_id" Type="customer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.admins" Member="admins">
    <Type Name="admin">
      <Column Name="admin_id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="first_name" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="image" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="last_name" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="username" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="admin_admin_role" Member="admin_roles" ThisKey="admin_id" OtherKey="admin_id" Type="admin_role" />
    </Type>
  </Table>
  <Table Name="dbo.cart_items" Member="cart_items">
    <Type Name="cart_item">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="unit_price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="shopping_cart_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="product_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="shopping_cart_cart_item" Member="shopping_cart" ThisKey="shopping_cart_id" OtherKey="shopping_cart_id" Type="shopping_cart" IsForeignKey="true" />
      <Association Name="product_cart_item" Member="product" ThisKey="product_id" OtherKey="product_id" Type="product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.categories" Member="categories">
    <Type Name="category">
      <Column Name="category_id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="is_activated" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="category_product" Member="products" ThisKey="category_id" OtherKey="category_id" Type="product" />
    </Type>
  </Table>
  <Table Name="dbo.cities" Member="cities">
    <Type Name="city">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="country_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="city_customer" Member="customers" ThisKey="id" OtherKey="name" Type="customer" />
      <Association Name="country_city" Member="country" ThisKey="country_id" OtherKey="country_id" Type="country" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.country" Member="countries">
    <Type Name="country">
      <Column Name="country_id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="country_city" Member="cities" ThisKey="country_id" OtherKey="country_id" Type="city" />
    </Type>
  </Table>
  <Table Name="dbo.customer_role" Member="customer_roles">
    <Type Name="customer_role">
      <Column Name="customer_id" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="role_id" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="customer_customer_role" Member="customer" ThisKey="customer_id" OtherKey="customer_id" Type="customer" IsForeignKey="true" />
      <Association Name="role_customer_role" Member="role" ThisKey="role_id" OtherKey="role_id" Type="role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.customers" Member="customers">
    <Type Name="customer">
      <Column Name="customer_id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="country" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="first_name" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="last_name" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="phone_number" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="username" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="name" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="customer_shopping_cart" Member="shopping_carts" ThisKey="customer_id" OtherKey="customer_id" Type="shopping_cart" />
      <Association Name="customer_customer_role" Member="customer_roles" ThisKey="customer_id" OtherKey="customer_id" Type="customer_role" />
      <Association Name="customer_forgot_password_token" Member="forgot_password_tokens" ThisKey="customer_id" OtherKey="customer_id" Type="forgot_password_token" />
      <Association Name="customer_order" Member="orders" ThisKey="customer_id" OtherKey="customer_id" Type="order" />
      <Association Name="city_customer" Member="city" ThisKey="name" OtherKey="id" Type="city" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.forgot_password_token" Member="forgot_password_tokens">
    <Type Name="forgot_password_token">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="expire_date_time" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="is_used" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="token" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="customer_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="customer_forgot_password_token" Member="customer" ThisKey="customer_id" OtherKey="customer_id" Type="customer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.order_detail" Member="order_details">
    <Type Name="order_detail">
      <Column Name="order_detail_id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="order_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="product_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="order_order_detail" Member="order" ThisKey="order_id" OtherKey="order_id" Type="order" IsForeignKey="true" />
      <Association Name="product_order_detail" Member="product" ThisKey="product_id" OtherKey="product_id" Type="product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.orders" Member="orders">
    <Type Name="order">
      <Column Name="order_id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="delivery_date" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="is_accept" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="order_date" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="order_status" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="payment_method" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tax" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="total_price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="customer_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="order_order_detail" Member="order_details" ThisKey="order_id" OtherKey="order_id" Type="order_detail" />
      <Association Name="customer_order" Member="customer" ThisKey="customer_id" OtherKey="customer_id" Type="customer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.permissions" Member="permissions">
    <Type Name="permission">
      <Column Name="permission_id" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="permission_role_permission" Member="role_permissions" ThisKey="permission_id" OtherKey="permission_id" Type="role_permission" />
    </Type>
  </Table>
  <Table Name="dbo.products" Member="products">
    <Type Name="product">
      <Column Name="product_id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cost_price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="current_quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="image" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="is_activated" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="sale_price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="category_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="product_cart_item" Member="cart_items" ThisKey="product_id" OtherKey="product_id" Type="cart_item" />
      <Association Name="product_order_detail" Member="order_details" ThisKey="product_id" OtherKey="product_id" Type="order_detail" />
      <Association Name="category_product" Member="category" ThisKey="category_id" OtherKey="category_id" Type="category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.role_permission" Member="role_permissions">
    <Type Name="role_permission">
      <Column Name="role_id" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="permission_id" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="is_permit" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="permission_role_permission" Member="permission" ThisKey="permission_id" OtherKey="permission_id" Type="permission" IsForeignKey="true" />
      <Association Name="role_role_permission" Member="role" ThisKey="role_id" OtherKey="role_id" Type="role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.roles" Member="roles">
    <Type Name="role">
      <Column Name="role_id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="role_admin_role" Member="admin_roles" ThisKey="role_id" OtherKey="role_id" Type="admin_role" />
      <Association Name="role_customer_role" Member="customer_roles" ThisKey="role_id" OtherKey="role_id" Type="customer_role" />
      <Association Name="role_role_permission" Member="role_permissions" ThisKey="role_id" OtherKey="role_id" Type="role_permission" />
    </Type>
  </Table>
</Database>